- name: netplan apply
  shell: netplan apply

- name: systemd-resolved
  service:
      name: systemd-resolved
      state: restarted
      enabled: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
