- name: install python pip and docker
  apt:
    state: latest
    name: ['docker.io', 'python-pip', 'python3-pip']

- name: Install docker and requests python modules
  pip:
    name:
      - docker
      - requests>=2.20.1


- name: Wordpress Docker Container
  docker_container:
      name: wordpress
      image: wordpress:latest
      detach: True
      published_ports:
      - 8080:80
      env: 
         WORDPRESS_DB_USER={{ db_user }},
         WORDPRESS_DB_HOST=joyo.com:3306,
         WORDPRESS_DB_PASSWORD={{ db_password }},
         WORDPRESS_DB_NAME={{ db_name }}
      dns_servers:
        - 192.168.56.102
        - 192.168.56.103
