---
- name: Install Apache2 and PHP
  hosts: wordpress
  become: yes
  tasks:
  - name: Install Apache2
    apt: 
      name=apache2 
      update_cache=yes 
      state=latest
      
  - name: Install PHP and MySQL modules for Apache2 and Wordpress
    apt: 
      name: ['libapache2-mod-php', 'php', 'php-mysql', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip']
      update_cache: yes 
      state: latest


  - name: Download wordpress
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
      validate_certs=no

  - name: Extract wordpress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/html/
      copy: no
      extra_opts: [--strip-components=1]

  - name: Copy sample config file
    command: mv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

  - name: Config wordpress
    lineinfile:
      path: /var/www/html/wp-config.php
      regexp: "{{item.regexp}}"
      line: "{{item.line}}"
    with_items:
      - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{ db_name }}' );"}
      - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{ db_user }}' );"}
      - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{ db_password }}' );"}
    notify:
      - restart apache2

        
  handlers:
    - name: restart apache2
      service: 
        name=apache2 
        state=restarted


- name: Install and configure MySQL
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySQL
    apt: 
      name=mysql-server
      update_cache=yes 
      state=latest

  - name: Install python modules for ansible
    apt: 
      name: ['python-pip', 'python-setuptools', 'libmysqlclient-dev', 'python-dev']
      update_cache: yes 
      state: latest

  - name: Create database
    mysql_db:
      name: "{{ db_name }}"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Create database user
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: 'wordpress.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
