- name: Install bind9
  apt: 
    name=bind9 
    state=latest

- name: configure bind
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
    - restart bind
    - check conf

- name: configure bind.local
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - restart bind
    - check conf

- name: check zone hash
  copy:
    content: "{{ records|hash }}"
    dest: /etc/bind/db.joyo.hash
  when: dns_role == "master"
  notify:
    - get timestamp
    - upload bind zone
    - restart bind
    - bind reload db

- name: config db ptr
  template:
    src: templates/db.joyo.ptr.j2
    dest: /etc/bind/db.joyo.ptr
  when: dns_role == "master"
  notify:
    - restart bind
    - bind reload db

- name: start bind
  service:
    name: bind9
    state: started
    enabled: yes

- name: resolv.conf fix
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
