---
- name: Create Backup User on Backup Agent to manage Backup Server
  hosts: infra01
  become: yes
  tasks:
  - name: Create Backup Groups
    group:
      name: backup
      state: present
    
  - name: Create User Backup 
    user:
      name: "{{ item }}"
      password: ""
      groups: backup, sudo
      append: yes
      shell: /bin/bash
      state: present
      system: yes
    with_items:
    - backup 
    
  - name: Initialize SSH connection from host to VM1
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ item.key }}"
    with_items:
    - { name: backup , key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"}
    


  - name: Upload Private Key and Public Key to VM1
    copy:
      src: templates/id_rsa
      dest: ~/.ssh/ 
      mode: 0600
       
   
  - name: Upload Public Key to VM1
    copy:
      src: templates/id_rsa.pub
      dest: /home/backup/.ssh/ 

      
  - name: Upload Private Key and Public Key to VM1
    copy:
      src: templates/id_rsa
      dest: /home/backup/.ssh/ 
      mode: 0600
      
  - name: Upload Cron Scripts to VM1
    copy:
      src: files/cronscripts/["dnsBackup", "sqlBackup", "wpBackup"]
      dest: /etc/cron.d/
  - name: Install Duplicity
    apt:
      name: duplicity
      force_apt_get: yes
      state: latest
    become_user: backup
    become: yes

