---
- name: Initial setup
  hosts: all
  remote_user: user
  become: yes
  tasks:
    - name: Setup interface
      template:
        src: templates/enp0s8.j2
        dest: /etc/netplan/55-enp0s8.yaml
      notify:
        - netplan apply
        - fix dns

    - name: systemd-resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: no

  handlers:
    - name: netplan apply
      shell: netplan apply
      
    - name: fix dns
      template:
        src: resolv.conf.fix.j2
        dest: /etc/resolv.conf


- name: setup bind and dns records
  hosts: infra
  become: yes
  tasks:
    - name: Install bind9
      apt: 
        name=bind9 
        state=latest

    - name: configure bind
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
      notify:
        - restart bind
        - check conf

    - name: configure bind.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
      notify:
        - restart bind
        - check conf

    - name: check zone hash
      copy:
        content: "{{ records|hash }}"
        dest: /etc/bind/db.joyo.hash
      when: dns_role == "master"
      notify:
        - get timestamp
        - upload bind zone
        - restart bind
        - bind reload db

    - name: config db ptr
      template:
        src: templates/db.joyo.ptr.j2
        dest: /etc/bind/db.joyo.ptr
      when: dns_role == "master"
      notify:
        - restart bind
        - bind reload db

    - name: update dns servers in resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

  handlers:
    - name: get timestamp
      shell: "date +%s"
      register: timestamp

    - name: upload bind zone
      template:
        src: templates/db.joyo.j2
        dest: /etc/bind/db.joyo

    - name: check conf
      shell: named-checkconf

    - name: bind reload db
      shell: rndc reload

    - name: restart bind
      service:
        name: bind9
        state: restarted
