- name: create bind_exporter
  user: 
    name: bind
    shell: /sbin/nologin
- name: download go
  get_url:
    url: https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go1.13.3.linux-amd64.tar.gz

- name: folder
  file:
    path: /opt/go
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go
    remote_src: yes

- name: Create a symbolic link
  file:
    src: /opt/go/go/bin/go
    dest: /usr/local/bin/go
    state: link
- name: Check that the file exists
  stat:
    path: /root/go/src/github.com/digitalocean/bind_exporter/bind_exporter.go
  register: stat_result

- name: go get
  shell: "go get github.com/digitalocean/bind_exporter"
  when: stat_result.stat.exists == False

- name: copy binary
  copy:
    src: /root/go/bin/bind_exporter
    dest: /usr/local/bin/bind_exporter
    mode: u=rwx,g=rx,o=rx
    remote_src: yes

- name: make a service
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service

- name: start bind_exporter
  service:
    name: bind_exporter
    state: started
    enabled: yes

