---
- name: setup mysql and mysql_exporter
  hosts: infra02
  become: yes
  roles:
    - mysql
    - mysql_exporter

- name: setup bind and exporters
  hosts: Anakin
  become: yes
  roles:
    - bind
    - node_exporter
    

- name: prometheus
  hosts: infra02
  become: yes
  roles:
    - prometheus
    - grafana
- name: setup bind and exporters
  hosts: infra01
  become: yes
  roles:
    - apache
    - apache_exporter
